// var myName="vimal";
// console.log(myName);
// var count=34;
// console.log(count);
// console.log("count");
const uid="acd123";

var firstName="vimal";
var lastName="vijayan";
var country="india";
var emailId="vimalvijayan123@gmail.com";
var password="12345";
var cnfrmPassword="12345";
var courseCount=0;
var isLoggedInFromGoogle=false;

console.log(`
       your unique id is: ${uid}
       his firstname is: ${firstName}
       his lastname is: ${lastName}
       his country is: ${country}
       his emailid is: ${emailId}
       his password is: ${password}
       his coursecount is: ${courseCount}
       his  loggedaccount is: ${isLoggedInFromGoogle}

`);
console.log("welcome");
console.log("name is vimal");